### PR TITLE
New GoTrueClient handling, session management and PKCE flow

### PR DESCRIPTION
**Pull request by Aietes**
The supabaseClient/GoTrueClient handling has changed, a client is only created once. This should avoid the stack guard of GoTrue triggering a warning, since this ensures only one GoTrue client exists in a context, e.g. in the browser.

Implemented the PKCE flow, which is now available on all Supabase projects. Since it’s more secure, this should be the default setting. The `implicit` flow is still available by setting the authFlow in the modules `clientOptions`.

Retrieving, managing and persisting the session is now handled by the supabase-js library.

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

The plugins supabase.client.ts and supabase.server.ts have changed to reflect the new auth flow. The auth flow happens mainly on the client in the browser context. For this reason the redirect route `/confirm` is set to `{ssr:false}`. The exchangeCodeForSession is run automatically by the supabase-js library, triggered by the getSessionFromUrl: true option for the supabaseCLient set in supabase.client.ts. The respective tokens are stored in localStorage, and are only available in the browser/client side. The tokens are then made available to the server via cookies. The server session is created in useSupabaseUser via setSession() in a separate step.

Authorization is no longer checked in the useSupabaseClient composable, but requires the useSupabaseUser composable to be used. If the module option `redirect` is at its default value `true`, this is handled automatically by the middleware router, which checks for an existing session via the useSupabaseUser composable. If users of the module disable redirect, they have to take care of these checks themselves, which should be reflected in the documentation. If the useSupabaseUser composable is not used after the auth flow completes, there will be no authorized session on the server, as the check for a valid session and setSession method need to run at least once to create a valid server session. This will result in SSR hydration errors if SSR is enabled.

The changes will help with a couple of issues, most notably the stack guard of the GoTrueClient. The changes can also potentially simplify the use of the module, as the automatic redirect adds a sane default for routes and middleware (including the check for a user/authorized session), which makes the module work out of the box. Users basically just need to add a login page and confirm page, the rest will just work. More advanced users will be able to change this default behavior via the module settings.

Documentation still needs to be adapted, if the changes are accepted and rolled in to the module.

## Checklist:

- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

It's hard to write tests for an auth flow. I've written tests, but they will not run without complicated prerequisites, therefore it doesn't make sense to add them to the repo.

### CODE REVIEW

**Review by larbish — CHANGES_REQUESTED** [review]
Thank you so much @Aietes for your work. As we dicussed yesterday, here are the changes I've made:
- `useSupabaseUser` is returning a ref so we can watch on its reactive value (its value is set/unset inside the `onAuthStateChange`
- auth `setSession` logic has been moved in the `supabase.server` plugin. I understand your point, but it seems to me that it is better to keep the logic outside of the user composable. It should work even if people are not calling this composable (and not using the `redirect` option)
- `serverSupabaseUser` has been implemented back
- playground has been updated to match the modifications above

My changes are ready. Just ping me when I'm allowed to push. 

Concerning the doc updates, here are the modifications I have in mind:
- `serverSupabaseClient` is now returning a promise
- Module options and default values has changed
- `useSupabaseToken` does not exist no more
- `useSupabaseAuthClient` has been removed, we should only use the `useSupabaseClient`
- Auth redirect is the default behaviour => `/confirm` page must exists and must be configured in supabase auth dashboard: 
Screenshot 2023-08-01 at 08 48 36

Is there anything else I am missing ?

**Comment by larbish** [comment]
@Aietes Since we are using the `redirect` option by default, I think we should provide a `redirectOptions.exclude` option to exclude routes concerned by the guard. 

Something like this:
```ts [nuxt.config.ts]
  redirectOptions: {
    login: '/login',
    callback: '/confirm',
    exclude: ['home', 'public-page']
  }
```
should allows user to access those pages without being redirected to the `login` page. By default `login` and `callback` pages are excluded by default (current behaviour).

**Comment by Aietes** [comment]
The exclude option makes a lot of sense. As a user, it might make sense to organize pages into a folder, e.g. `public`. The exclude option could therefore support folders, making it easier to exclude multiple pages.

**Comment by Aietes** [comment]
I implemented the exclude option, it supports pages and folders. I also update the docs accordingly.

**Comment by ClineResearch** [comment]
Hello,
you have write : " The `implicit` flow is still available by setting the authFlow in the modules `clientOptions`."
how can I set "flowType" attribute with this "implicit" flow ? 
In my app, I don't use login and confirmation page. Instead, I use overlay to user authentication. It's seem that PKCE flow don't support this way of authentification. 
Thanks in advance!
JF

**Pull request merged**
