### PR TITLE
fix(types): added explicit types annotations for `serverSupabaseClient` and `serverSupabaseServiceRole`

### PR DESCRIPTION
**Pull request by th1m0**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Added explicit type annotations for `serverSupabaseClient` and `serverSupabaseServiceRole` as they lose the `Database` type when building.

### CODE REVIEW

**Comment by philliphartin** [comment]
With this addition, is there a simple way to use the Database types generated by the Supabase CLI?
https://supabase.com/docs/guides/api/rest/generating-types

**Comment by th1m0** [comment]
> With this addition, is there a simple way to use the Database types generated by the Supabase CLI? [supabase.com/docs/guides/api/rest/generating-types](https://supabase.com/docs/guides/api/rest/generating-types)

Yes you should no longer be needed to pass in the `Database` types in the functions `serverSupabaseClient` and `serverSupabaseServiceRole`

This should work fine: 
```ts
import { serverSupabaseClient } from '#supabase/server'

export default defineEventHandler(async (event) => {
	const client = await serverSupabaseClient(event)
})
```

`client` should have the types generated by the supabase cli automatically if you set the [`types` path](https://supabase.nuxtjs.org/get-started#types) correctly in `nuxt.config.ts`

This was also done for the composables in https://github.com/nuxt-modules/supabase/pull/404

**Review by larbish — APPROVED** [review]

**Comment by larbish** [comment]
Thanks 🙏

**Comment by Zebnastien** [comment]
> `client` should have the types generated by the supabase cli automatically if you set the [`types` path](https://supabase.nuxtjs.org/get-started#types) correctly in `nuxt.config.ts`

@th1m0, what do you mean ? You mean passing "paths" to "tsConfig" ? Or is there a better way ?

Thank you both for the work.

**Comment by th1m0** [comment]
@Zebnastien Thanks for reaching out! That would be a bug, could you please raise an issue about this?

**Comment by Zebnastien** [comment]
@th1m0
Done. Thanks!

**Pull request merged**
